version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: 100xdevweek11
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pswd
      POSTGRES_DB: week11
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: